Course.create(:subject => "Intro Biology", :level =>100)
Course.create(:subject => "Intro Biology II", :level =>100)
Course.create(:subject => "Ecology", :level => 200)

Relationship.create(:course_id => "3",:requisite_id => "1", :mandatory => true, :type => "prerequisite" )
Relationship.create(:course_id => "3",:requisite_id => "2", :mandatory => true, :type => "prerequisite" )


Course.create(:level => 151, :subject => "Introduction to Biological Science I")
Course.create(:level => 152, :subject => "Introduction to Biological Science II")
Course.create(:level => 218, :subject => "Cell Biology")
Course.create(:level => 310, :subject => "Genetics")
Course.create(:level => 317, :subject => "Ecology")
Course.create(:level => 301, :subject => "Comparative Vertebrate Anatomy")
Course.create(:level => 302, :subject => "Animal Embryology")
Course.create(:level => 309, :subject => "Entomology")
Course.create(:level => 312, :subject => "Invertebrate Zoology")
Course.create(:level => 313, :subject => "Vertebrate Natural History")
Course.create(:level => 391, :subject => "Topics in Biology")
Course.create(:level => 416, :subject => "Ornithology")
Course.create(:level => 417, :subject => "Mammalogy")
Course.create(:level => 435, :subject => "Herpetology")
Course.create(:level => 445, :subject => "Neurobiology and Behavior")
Course.create(:level => 491, :subject => "Topics in Biology")
Course.create(:level => 503, :subject => "Fish Biology")
Course.create(:level => 320, :subject => "Biology of the Seed Plant")
Course.create(:level => 321, :subject => "Plant Development")
Course.create(:level => 322, :subject => "Economic Botany")
Course.create(:level => 323, :subject => "Plant Physiology")
Course.create(:level => 391, :subject => "Topics in Biology")
Course.create(:level => 512, :subject => "Plant Diversity and Evolution")
Course.create(:level => 491, :subject => "Topics in Biology")

